name: "Flutter Build Deploy"
on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # *****************************************************
      # * SETUP
      # *****************************************************
      # 1. ADD THIS STEP FIRST TO FETCH YOUR CODE
      - uses: actions/checkout@v4

      # 2. Setup Flutter environment
      - uses: subosito/flutter-action@v2
        with:
          # バージョンの指定
          flutter-version: "3.13.4"
          # キャッシュの有効化
          cache: true

      # *****************************************************
      # * Build
      # *****************************************************
      - run: flutter pub get
      - run: flutter build web -t lib/main.dart --web-renderer canvaskit
